### ISSUE TITLE
Shows desktop instead of blank screen

### ISSUE THREAD

**Issue by Safari77** [mate-desktop/mate-screensaver#103]
When locking screen, either timeout or `mate-screensaver-command --lock`, screen does not blank, but instead shows desktop image at the time of locking. When I press any key, the password prompt comes up and the configured lockscreen image is shown OK.
Mate-desktop and mate-screensaver 1.16.0, gtk 3.22.0.

```
org.mate.power-manager lock-use-screensaver true
org.cinnamon.SessionManager autostart-blacklist ['gnome-settings-daemon', 'gnome-fallback-mount-helper', 'gnome-screensaver', 'mate-screensaver', 'mate-keyring-daemon', 'indicator-session', 'gnome-initial-setup-copy-worker', 'gnome-initial-setup-first-login', 'gnome-welcome-tour', 'xscreensaver-autostart', 'nautilus-autostart', 'caja', 'xfce4-power-manager']
org.mate.screensaver logout-enabled false
org.mate.screensaver lock-enabled true
org.mate.screensaver embedded-keyboard-enabled false
org.mate.screensaver logout-delay 120
org.mate.screensaver idle-activation-enabled true
org.mate.screensaver themes @as []
org.mate.screensaver logout-command ''
org.mate.screensaver embedded-keyboard-command ''
org.mate.screensaver mode 'blank-only'
org.mate.screensaver power-management-delay 30
org.mate.screensaver lock-delay 0
org.mate.screensaver cycle-delay 10
org.mate.screensaver lock-dialog-theme 'default'
org.mate.screensaver status-message-enabled true
org.mate.screensaver user-switch-enabled true
org.mate.SettingsDaemon.plugins.media-keys screensaver '<Control><Alt>l'
```
##

**Comment by bobi1024** [comment]
Same here.
debian testing
mate 1.16 compiled from source 
mate-screensaver compiled from source 1.16 release
libgtk 3.21.5-3

**Comment by gradinaruvasile** [comment]
Same here. Debian testing with Mate 16.0 from unstable, .
I have 2 monitors, one of the laptop display and the other is an external display. Intel Skylake graphics.
One of the monitors  (where the cursor is when locking)  shows the lock screen as it should, but the other monitor remains frozen at the last image it had.
With mate 14.2 it was working ok.
I had to resort to xscreensaver as a stopgap measure.

**Comment by gradinaruvasile** [comment]
Well. I ununstalled mate-screensaver, started xscreensaver then installed mate-screensaver again and now it is working as it should.

**Comment by arehtykitna** [comment]
@raveit65 mate-screensaver-1.16-01.fc25 is affected by this bug. All other screensavers in the package appear to work okay.

**Comment by fredo-m** [comment]
Hi,
I had the same bug, I had opened a bug report on Debian's bug tracker: 
[https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841642](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841642)

According to my tests, the bug is only for "blank screen" screen saver, the others work.
Is this the same problem that Caja had with the management of desktop background image?

Regards.

**Comment by pwaller** [comment]
I thought I'd have a go at bisecting this on debain sid. Built version 0.14 from source, but the bug persists there, making me think it may instead be a problem with the x server or something else, rather than mate-screensaver per-se. @gradinaruvasile can you confirm that **just** changing to 0.14 fixes the issue? (And nothing else was changed?) What do you need to change to make it work?

**Comment by gradinaruvasile** [comment]
@pwaller 
Unfortunately i don't have time to test much, but what i observed is the following:
Using versions up to 1.14.2 i had no issues like this. When 1.16 was in unstable i upgraded to it and i saw this issue. I downgraded to 1.14.2, it went away. I did this on 2 separate computers and both behaved the same way (both had 2 monitors). So at that point the version of the screensaver was the deciding factor. Since then many components were upgraded and 1.14 is not available anymore.
Also, as @fredo-m pointed out, this bug does not manifest when using other themes than "blank screen" (i now use the matrix theme and it's ok but i would still like to have a real screensaver).

**Comment by raveit65** [comment]
It is only a problem with blank screensaver theme. I have 2 reports about in fedora 25.
https://bugzilla.redhat.com/show_bug.cgi?id=1398831
https://bugzilla.redhat.com/show_bug.cgi?id=1397900
But i have m-s gtk3 also running on fedora 24, so i check if it makes a different with another xorg-server version.

**Comment by monsta** [comment]
Now I have this as well... with GTK+ 3.22.5 and blank theme.

**Comment by monsta** [comment]
Ok, fixed by https://github.com/mate-desktop/mate-screensaver/pull/110.
