### ISSUE TITLE
Local security vulnerability in screen locking.

### ISSUE THREAD

**Issue by j3pic** [mate-desktop/mate-screensaver#182]
#### Expected behaviour

If you close a laptop running MATE and then re-open it, you shouldn't see your open windows before the password prompt appears.

#### Actual behaviour

When I open the lid, the unlocked desktop appears for a split-second, and then it disappears and the password prompt appears. 

This is a security vulnerability because the information in the open windows is leaked to whoever opens the laptop. 

#### Mitigation

Owners of laptops running MATE should take extra care to explicitly lock the screen before closing the lid. This prevents the contents of your desktop from leaking if someone you don't trust opens the lid.

#### Steps to reproduce the behaviour

1. Log into a MATE session on a laptop.
2. Close the lid.
3. Open the lid.
4. If you don't see it, try it on a laptop running the proprietary NVidia driver.

#### MATE general version

1.20.0

#### Package version

mate-screen-saver 1.20.0-1

#### Linux Distribution

Pop! OS 18.04 LTS (based on Ubuntu)

#### Link to downstream report of your Distribution

None. They would just tell me to report upstream anyway.

**Comment by bwat47** [comment]
duplicate of #145

Check my comment here for a workaround: https://github.com/mate-desktop/mate-screensaver/issues/145#issuecomment-454250088

**Comment by lukefromdc** [comment]
That looks like the package version is the same as both Ubuntu and Debian. Thus a report to Ubuntu might be accepted, while Debian (two generations away) would be more likely to close it as Ubuntu differs quite a bit from Debian.

**Comment by don-clugston-sociomantic** [comment]
I can confirm this. I consider this to be of absolute maximum severity. This is product recall territory. Nobody should be using a distro with a flaw like this.
This bug is probably the same thing. I can confirm this as well.
https://forums.linuxmint.com/viewtopic.php?t=285345

**Comment by lukefromdc** [comment]
A number of issues of this sort come from MATE drawing the screensaver on VT7 same as the desktop and everything else. X does not recognize a screensaver window as different than anything else, and thus does not prioritize it. 

I think it's GNOME screensaver that cut the Gordian knot on this by executing a VT switch to another VT for the screensaver, so that if the screensaver window does not get drawn for any reason a black screen instead of the desktop showing results. Someone at GNOME got sick of playing whack-a-mole with these issues and fixed it right.

MATE btw does not depend on or require any particular screensaver, and gnome-screensaver does not depend on gnome-shell, clutter etc so you probably could install it and set it in startup applications to run as your screensaver as a workaround until someone who knows the screensaver code (I am not familiar with this part of the code myself) can get it fixed. Anyway, there's no reason to ditch all of MATE (which is a desktop environment, not a distro) because of an issue with the screensaver when other screensavers can be substituted. As for "product recalls" we are not selling a product in the first place, the equivalent here is a immediate point release when a bug is fixed and distros recognizing its importance and getting it out the door quickly and at high priority. This happened with APT a while ago in Debian based distros and led to Ubuntu point releases (for the whole distro) all the way back to 14.04 LTS as the issue fixed was one that could allow package interception and replacement.

I do not have a "normal" laptop to test this issue with, only a converted Chromebook (Debian Unstable installed) and I always set them up to totally ignore closing the lid so I can put it in my bag while letting a long job (e.g. a video render that can take over an hour) keep runnng. I do not know if suspend on closing the lid would even work with that machine and would not want to have problems disabling it again. That machine of course does not have Nvidia graphics, those kind of laptops are out of my price range.

I myself rely on encryption and total shutdown for any computer (desktop or laptop) that needs to be protected from another person accessing it. Laptops can easily be stolen or just plain left behind, and I am used to dealing with state-level attackers who would get past any screensaver with ease.

**Comment by don-clugston-sociomantic** [comment]
Undoubtedly a screen lock is no match for a seasoned hacker. However in this case all a person needs to do is start recording video on their phone, and press a key on the machine to awake from hibernation. Even a small child could do this.

I really don't care about what workarounds exist. The issue makes MATE unusable in a commercial environment. Now with the GDPR, a company has a risk of fines exceeding €10 million for security breaches. No company wants to expose itself to this level of risk.

**Comment by lukefromdc** [comment]
DO keep in mind that we at MATE are not paid product support, corporate users can buy that from Red Hat Enterprise Linux or Ubuntu.  Someone else on the team will have to work on this, I normally develop on the desktop, had trouble getting my converted chromebook to ignore closing the lid, and I have limited time.  I do not know the screensaver code well enough to work on this, having only recently gotten it to work at all with a local build (which on Debian requires a patch).

**Comment by phocean** [comment]
> I do not have a "normal" laptop to test this issue with, only a converted Chromebook (Debian Unstable installed) and I always set them up to totally ignore closing the lid so I can put it in my bag while letting a long job (e.g. a video render that can take over an hour) keep runnng.

The issue is also there when you simply suspend from the menu or whatever method.
The only workaround that works is to first lock the screen, manually, and then close the lid to trigger suspending.

> I myself rely on encryption and total shutdown for any computer (desktop or laptop) that needs to be protected from another person accessing it. Laptops can easily be stolen or just plain left behind, and I am used to dealing with state-level attackers who would get past any screensaver with ease.

Disk encryption is not addressing the same issue at all. Encryption is useless if an attacker can take a photo of the screen, or, worse, bypass it because it's buggy or did not trigger because the mouse cursor was inside a text box (if you did not know, this is another terrible issue).

As I said in the other bug report, it would be nice that Mate uses this project instead:

https://github.com/google/xsecurelock

**Comment by lukefromdc** [comment]
Disk encryption's job is to protect your data when and only the machine is all the way off. If the machine is suspended, the disk is NOT locked and its contents can be copied. A skilled attacker can recover disk keys by a "cold boot attack" from a running machine. The screenlocker's job is to protect your application state while you are in the toilet and friendlies are present, but not watching that closely. 

To do this right (with no more of these bugs) would probably require a vt-switch to kill all of the race condition and multimonitor bugs at once. As I have said elsewhere, it is very, very difficult to create a "secure" screenlocker on X on the same VT that X is running on, as X has no way to prioritize the screensaver over any other window.  Anything less is literally the same to X as a video player that must always fullscreen over all monitors (no matter what monitors are use, plugged, unplugged etc), must always be the first window to come up when a monitor is added, turned on, or the machine is brought out of suspend, and must always divert any new keyboard, mouse, or other added input device to itself. Wayland devs have cited this as a specific security problem with Xorg.

Thus, someone here more familiar with the screensaver's expected behavior and its code than I am (I only recently found out how to get it to work at all on Debian from a local build) ideally would port over the gnome-screensaver commits for the vt-switch.

Lastly, if you close your laptop's lid and then leave it where hostile parties have access. you are going to have much bigger problems than any failure of the screenlocker. Mostly likely any attacker will simply slide the entire machine into their bag and steal it. Then, posession=root and you are fscked if you left it running or did not encrypt it. The screenlocker is probably more important on a desktop in a large room environment(everyone needs to take toilet breaks) than on a laptop(which you can and should take with you even to the toilet if you want to keep it.)

**Comment by phocean** [comment]
> I DO agree this is an ugly bug

Then, the purpose of this long text is not clear and pretty out of place. By posting here, I am talking to the project.

Moreover, I learned strictly nothing : I am a pentester and infosec trainer.

We are neither here to discuss threat models, that would vary to every individuals or organization, nor how it is difficult in general when it has apparently been solve by other DE and several projects.

We are here in the expectation to fix a security vulnerability, which, by the way, should have a CVE, and should be treated differently than other classes of bugs.

I mean, with more reaction and higher priorities than it seems to be the case.

Again, if manpower to maintain this piece of code is lacking, there are yet many other ways to solve it.

**Comment by phocean** [comment]
Also, one annoying thing at least in Ubuntu Mate, is that mate-screensaver is a core dependency.

Thus, there is no way to remove it in a clear manner, so that users can implement their own solution, based on light-locker or any other lockers.

**Comment by lukefromdc** [comment]
You should be able to emove the toplevel metapackage and keep all the actual MATE code,
or go to mate-control-center startup applicarions and set it not to start

**Comment by lukefromdc** [comment]
I am not the one ro fix this, other team members need to respond. Some of
what you said read like attacks on us and may have discouraged response.
Also this is the sexond report of tgis, the first report is where anything would most
likely take place ahd has more tech information. Thus this duplcate should be 
closed, but I am on thr road abd cannnot do it from here.

**Comment by lukefromdc** [comment]
Closing as DUPLICATE of https://github.com/mate-desktop/mate-screensaver/issues/145 , which is where this should be worked on.

**Comment by Phoenix09** [comment]
I'm still seeing this behaviour when closing the lid with suspend disabled (#145 is specifically relating to suspend so not sure that's the right place for this)
Ubuntu 20.04
mate-screensaver 1.24.0
