### ISSUE TITLE
Unable to switch user

### ISSUE THREAD

**Issue by stevew-Purdue** [mate-desktop/mate-screensaver#64]
OS and version: Ubuntu 14.04
mate-screensaver-command version: 1.8.1
display manager: lightdm

When attempting to switch user from the MATE screensaver, nothing happens.  After unlocking the screensaver I see a popup window with the following displayed:
    Unable to start new display
    Could not identify the current session.

Please let me know if you need any additional information.

Thanks!

Steve

**Comment by NiceandGently** [comment]
@stevew-Purdue 
Do you have a second DM installed?

**Comment by stevew-Purdue** [comment]
On 05/20/2015 02:40 PM, No_name wrote:
>
> @stevew-Purdue <https://github.com/stevew-Purdue>
> Do you have a second DM installed?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mate-desktop/mate-screensaver/issues/64#issuecomment-103990099>.
>

Yes, I do.  I found that I had to remove the libgdm1 and gnome-session 
packages to correct the problem.

Steve

**Comment by NiceandGently** [comment]
Ok, we have changed to detect which DM is installed to which DM is running
https://github.com/mate-desktop/mate-session-manager/commit/a5289a48ecfbfbe0147551f6dee13d58ee17b033
and
https://github.com/mate-desktop/mate-screensaver/commit/269333e2683e6dd9975f298267cac177b889541a
So, this issue is fixed
@flexiondotorg 
please close it
