### ISSUE TITLE
mate-screensaver conflicts with gnome-screensaver

### ISSUE THREAD

**Issue by risto3** [mate-desktop/mate-screensaver#93]
Hi, I'm experiencing conflicts with gnome-screensaver in share/applications/screensavers/*.desktop
It would be great to have these conflicts removed, perhaps by simply prepending 'mate-' to the names of the file (and any potential reference to them).

Noticed on pkgsrc wip mate-screensaver-1.14.0

**Comment by raveit65** [comment]
Which conflict?
and as always....
Which distro?
Btw. gnome-screensaver is obsolete since years, gnome-shel don't use it anymore.

**Comment by risto3** [comment]
As I mentioned, pkgsrc, which still has gnome2, which I run on an illumos distro called OmniOS
(SunOS 5.11 i386)

The conflict is as follows if gnome2 is installed (which I'd like to stop using once Mate tested):
```
richard@omnis:/home/richard/src/pkgsrc/wip/mate-screensaver$ bmake install
=> Bootstrap dependency digest>=20010302: found digest-20160304
=> Becoming ``root'' to make su-real-package-install (pfexec)
===> Installing binary package of mate-screensaver-1.14.0
pkg_add: Conflicting PLIST with gnome-screensaver-2.30.2nb23: share/applications/screensavers/cosmos-slideshow.desktop
pkg_add: 1 package addition failed
```

**Comment by raveit65** [comment]
Ok, looks like you're using a very old distro with gnome-screensaver-2.30.2nb23.
But all this stuff is removed from g-s since a long time.
https://git.gnome.org/browse/gnome-screensaver/commit/?id=2a930fdc0ad5d16eb6cc8619cb6fe76993e0f8ab
https://git.gnome.org/browse/gnome-screensaver/commit/?id=897dc79ba04b3cfb49b93f6bd03fa2ce59a274b7
For this reason we never saw this conflict.
And latest version is 3.6 which seems to be used by ubuntu unity only.
For me it sounds a bit odd to rename cosmos screensaver for an
a) old version of a package
b) a package which is in general not under gnome development anymore.

Imo, your package maintainer is responsible to fix conflicts with other packages.
Did you file out out a report there?

**Comment by risto3** [comment]
Currently, the package is marked 'CONFLICTS+=    gnome-screensaver-[0-9]*'
which, naturally, prevents it from installing and overwriting an existing file.
I'm asking, such as for 'mate-applets', to get to the point where no conflicts exist any longer.
This greatly simplifies things for users.

**Comment by raveit65** [comment]
I wanna hear the opinion of the mate maintainer of your distro.
So again, is a downstream report file out?

**Comment by risto3** [comment]
as to the "downstream" report, I should mention that pkgsrc is primarily a community-based 
maintainership... we just celebrated our 50th quarterly release. 

I did ask some others to comment here that have been instrumental in bringing the mate desktop into pkgsrc-wip (which is preparation for an eventual inclusion into the mainline pkgsrc repository).
I guess to repeat the point, pkgsrc currently supports both gnome2 and gnome3.

**Comment by raveit65** [comment]
Don't understand me wrong but all this is a bit unclear?
What is pkgsrc? Is that a repo from your distro?
Or something which is distro independent?
From my point of view gnome-2 is un-maintained and didn't got updates since 2010, means using gnome-2 is very insecure if it isn't maintained by by a distro itself, ie. rhel-/centos-5/6, which are LTS releases.
And Mate is there to replace gnome-2.
So the right way is to replace gnome2 with MATE in pkgsrc, what ever that is.....
I'm in doubt to change something from our side for something which is pretty obsolete and didn't have a future.
For that reason we need a statement from maintainer and more infos what pkgsrc is.
Thank you

**Comment by risto3** [comment]
I guess the question is based upon choice. It is possible that there may still be users of gnome2
that are not in a position nor want to migrate [solely] to anything else (perhaps OpenIndiana, for example). 

http://pkgsrc.org/  and http://pkgsrc.se/ may provide some information you seek.

**Comment by raveit65** [comment]
Can you you provide a list of all paths where cosmos screensaver from gnome is installed?

**Comment by raveit65** [comment]
Ok, it looks like that pkgsrc is based on rhel6 for linux
https://pkgsrc.joyent.com/packages/Linux/el6/2014Q2/x86_64/x11/

**Comment by raveit65** [comment]
Based on gnome-screensaver-2.30.2nb21.tgz we have 2 conflicting paths
/usr/share/backgrounds/cosmos/
/usr/share/applications/screensavers/

**Comment by raveit65** [comment]
Hmm, but where is mate-screensaver ?
http://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/README-all.html
https://pkgsrc.joyent.com/packages/Linux/el6/2014Q2/x86_64/All/
Is there a chance to contact the packager of mate-screensaver?
Changing installed directories can also be done by creating the package.

**Comment by raveit65** [comment]
Hmm, one more conflict file
/share/pixmaps/gnome-logo-white.svg

**Comment by risto3** [comment]
for wip, the main page is https://pkgsrc.org/wip/
you can browse the git repository on the pkgsrc-wip git repository.

**Comment by risto3** [comment]
the PLIST is the file containing the references currently installed.

**Comment by monsta** [comment]
Wait... co-installing MATE on some old system with Gnome 2? :open_mouth:

**Comment by risto3** [comment]
Why Mr BILL?
