### ISSUE TITLE
mate-screensaver does not cover all monitors

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [mate-desktop/mate-screensaver#98]
Hi

i'm running a slightly odd monitor setup.

```
$ xrandr | grep connected
DP2-1 connected 1920x1080+1920+1080 (normal left inverted right x axis y axis) 531mm x 299mm
DP2-2 connected 1080x2560+3840+0 left (normal left inverted right x axis y axis) 677mm x 290mm
DP2-3 connected primary 1920x1080+0+1080 (normal left inverted right x axis y axis) 510mm x 290mm
```

```
$ mate-screensaver --version
mate-screensaver 1.14.1
```

when the screensaver locks my screen, the DP2-2 is no correctly covered and you can read all the informations visible on that screen. you cannot interact with the visible windows.
##

**Comment by steelwing** [comment]
I can reproduce this on ArchLinux with mate-screensaver 1.14.1, except I am able to interact with any windows that are visible.  It only happens if my mouse cursor is on my left monitor when the screensaver activates, not if it's on the right-hand monitor.
Monitor setup:
`
DFP2 connected 1600x900+1280+0 (normal left inverted right x axis y axis) 443mm x 249mm
CRT1 connected primary 1280x1024+0+0 (normal left inverted right x axis y axis) 338mm x 270mm
`
Anyone know if this is still happening in 1.15.x or above?

**Comment by gradinaruvasile** [comment]
At least on Debian Testing It happens on 1.16.0 too (it was working well with 1.14.2).

**Comment by stenrose** [comment]
It happens with 1.16.0-2 on Arch Linux too.

**Comment by gradinaruvasile** [comment]
I can confirm that using other than "Blank Screen" the screensaver covers all monitors. On Intel (Skylake) and AMD (r600g) hardware.

Debian testing, mate-screensaver 1.16.0-1.
